import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getInstallationOctokit } from '@/lib/github';
import { summarizeIssue } from '@/lib/ai';

export async function POST(req: Request) {
    const { eventId } = await req.json();
    if (!eventId) return NextResponse.json({ error: "Missing eventId"}, { status: 400 });

    const event = await prisma.eventLog.findUnique({ where: { id: eventId }, include: { repository: true } });
    if (!event || event.status !== 'PENDING') return NextResponse.json({ message: "Not pending" });

    try {
       const payload = event.payload as any;
       const eventType = event.eventType;
       let actionDetails = "";

       // 1. Process "issues.opened"
       if (eventType === 'issues' && payload.action === 'opened') {
           const issue = payload.issue;
           const repo = payload.repository;
           const installationId = payload.installation?.id;

           // Step A: Generate AI Summary
           const summary = await summarizeIssue(issue.title, issue.body);
           
           // Step B: Post Comment to GitHub
           if (installationId) {
               const octokit = await getInstallationOctokit(installationId);
               await octokit.rest.issues.createComment({
                   owner: repo.owner.login,
                   repo: repo.name,
                   issue_number: issue.number,
                   body: `**AI Summary:**\n${summary}\n\n*This comment was automatically generated by the Event-Driven Bot.*`
               });
               actionDetails += "Added AI comment to GitHub. ";
           }

           // Step C: Send Slack Notification
           const slackWebhook = process.env.SLACK_WEBHOOK_URL;
           if (slackWebhook) {
               await fetch(slackWebhook, {
                   method: 'POST',
                   headers: { 'Content-Type': 'application/json' },
                   body: JSON.stringify({
                       text: `🚨 *New Issue Opened*: <${issue.html_url}|${issue.title}>\n*Repository*: ${repo.full_name}\n*Summary*: ${summary}`
                   })
               });
               actionDetails += "Sent Slack notification. ";
           } else {
               actionDetails += "Slack skipped — SLACK_WEBHOOK_URL not configured. ";
           }
       } else {
           actionDetails = `Ignored event: ${eventType}.${payload?.action}`;
       }
       
       // Mark as processed
       await prisma.eventLog.update({
          where: { id: eventId },
          data: { status: 'PROCESSED', processedAt: new Date() }
       });

       // Log the action
       if (actionDetails) {
           await prisma.actionLog.create({
               data: {
                   eventId: event.id,
                   actionType: 'automated_response',
                   details: actionDetails,
                   status: 'SUCCESS'
               }
           });
       }

       return NextResponse.json({ success: true });
    } catch (e: any) {
       console.error("Processing error:", e);
       await prisma.eventLog.update({
          where: { id: eventId },
          data: { status: 'FAILED', error: e.message }
       });
       return NextResponse.json({ error: "Processing failed" }, { status: 500 });
    }
}
